# Generated by Django 5.2.12 on 2026-04-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stemming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.CharField(max_length=255, verbose_name='Kata Asli')),
                ('stem', models.CharField(max_length=255, verbose_name='Kata Dasar')),
                ('frek', models.IntegerField(default=0, verbose_name='Frekuensi')),
            ],
        ),
    ]
