# Generated by Django 5.2.12 on 2026-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KamusSunda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata_dasar', models.CharField(max_length=255, unique=True, verbose_name='Kata Dasar')),
                ('arti', models.TextField(verbose_name='Arti Bahasa Indonesia')),
            ],
            options={
                'verbose_name_plural': 'Data Kamus Sunda',
            },
        ),
        migrations.CreateModel(
            name='StemmingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.CharField(max_length=255, verbose_name='Kata Asli')),
                ('stem', models.CharField(max_length=255, verbose_name='Kata Dasar (Hasil)')),
                ('arti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arti')),
                ('frek', models.IntegerField(default=1, verbose_name='Frekuensi')),
                ('status_manual', models.CharField(choices=[('Benar', 'Benar'), ('Salah', 'Salah')], default='Salah', max_length=10, verbose_name='Validasi Akurasi')),
                ('tanggal_proses', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stemming',
        ),
    ]
