# Generated by Django 5.2.12 on 2026-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0002_kamussunda_stemmingresult_delete_stemming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stemmingresult',
            name='arti',
        ),
        migrations.RemoveField(
            model_name='stemmingresult',
            name='status_manual',
        ),
        migrations.RemoveField(
            model_name='stemmingresult',
            name='stem',
        ),
        migrations.RemoveField(
            model_name='stemmingresult',
            name='tanggal_proses',
        ),
        migrations.AddField(
            model_name='stemmingresult',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stemmingresult',
            name='manual_stem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stemmingresult',
            name='stem_sistem',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='frek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='tokens',
            field=models.CharField(max_length=255),
        ),
    ]
