# Generated by Django 5.2.12 on 2026-04-15 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0003_remove_stemmingresult_arti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stemmingresult',
            name='stem_sistem',
        ),
        migrations.AddField(
            model_name='stemmingresult',
            name='stem',
            field=models.CharField(default='', max_length=255, verbose_name='Kata Dasar (Hasil)'),
        ),
        migrations.AddField(
            model_name='stemmingresult',
            name='tanggal_proses',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kamussunda',
            name='arti',
            field=models.TextField(blank=True, null=True, verbose_name='Arti Bahasa Indonesia'),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='tokens',
            field=models.CharField(max_length=255, verbose_name='Kata Asli'),
        ),
    ]
