# Generated by Django 5.2.12 on 2026-04-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0004_remove_stemmingresult_stem_sistem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stemmingresult',
            name='manual_stem',
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='frek',
            field=models.IntegerField(default=0, verbose_name='Frekuensi'),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Validasi'),
        ),
    ]
