# Generated by Django 5.2.12 on 2026-04-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0005_remove_stemmingresult_manual_stem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kamussunda',
            options={},
        ),
        migrations.AlterField(
            model_name='kamussunda',
            name='arti',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kamussunda',
            name='kata_dasar',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='frek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='stem',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='tokens',
            field=models.CharField(max_length=255),
        ),
    ]
