# Generated by Django 5.2.12 on 2026-04-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0006_alter_kamussunda_options_alter_kamussunda_arti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stemmingresult',
            name='tanggal_proses',
        ),
        migrations.AddField(
            model_name='stemmingresult',
            name='arti',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stemmingresult',
            name='status_manual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kamussunda',
            name='arti',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kamussunda',
            name='kata_dasar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='frek',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='stem',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stemmingresult',
            name='tokens',
            field=models.CharField(max_length=100),
        ),
    ]
