# Generated by Django 5.2.12 on 2026-04-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0007_remove_stemmingresult_tanggal_proses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stemmingresult',
            name='status_manual',
            field=models.CharField(default='Otomatis', max_length=50),
        ),
    ]
