# Generated by Django 5.2.12 on 2026-05-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0008_alter_stemmingresult_status_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stemmingresult',
            name='arti',
        ),
    ]
