# Generated by Django 5.2.12 on 2026-05-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0009_remove_stemmingresult_arti'),
    ]

    operations = [
        migrations.CreateModel(
            name='KamusStopword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata_stopword', models.CharField(max_length=100)),
                ('arti', models.CharField(max_length=100)),
            ],
        ),
    ]
