# Generated by Django 5.2.12 on 2026-05-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0010_kamusstopword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kamusstopword',
            old_name='arti',
            new_name='indonesian',
        ),
        migrations.RenameField(
            model_name='kamusstopword',
            old_name='kata_stopword',
            new_name='sundanese',
        ),
    ]
