# Generated by Django 5.2.12 on 2026-05-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemming', '0011_rename_arti_kamusstopword_indonesian_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kamusstopword',
            old_name='indonesian',
            new_name='arti',
        ),
        migrations.RenameField(
            model_name='kamusstopword',
            old_name='sundanese',
            new_name='kata_stopword',
        ),
    ]
